# Generated by Django 5.2.5 on 2025-09-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255, verbose_name='插件名称')),
                ('description', models.TextField(verbose_name='插件描述')),
                ('code', models.CharField(max_length=255, verbose_name='插件编码')),
                ('scope', models.CharField(choices=[('STORE', 'STORE'), ('PARSING', 'PARSING')], max_length=20, verbose_name='插件作用域')),
                ('config', models.JSONField(verbose_name='插件配置')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='插件状态')),
                ('version', models.CharField(max_length=20, verbose_name='插件版本')),
                ('author', models.CharField(max_length=255, verbose_name='插件作者')),
                ('tags', models.CharField(default='', help_text='逗号分隔', max_length=1000, verbose_name='插件标签')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL, verbose_name='更新用户')),
            ],
            options={
                'verbose_name': '插件',
                'verbose_name_plural': '插件',
                'db_table': 'plugin',
                'unique_together': {('code', 'version')},
            },
        ),
    ]
