# Generated by Django 5.2.5 on 2025-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrdefinitionmodel',
            name='attr_label',
            field=models.CharField(default='attrlabel', max_length=255, verbose_name='属性标签'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attrdefinitionmodel',
            name='attr_description',
            field=models.TextField(blank=True, null=True, verbose_name='属性描述'),
        ),
        migrations.AlterField(
            model_name='attrdefinitionmodel',
            name='attr_id',
            field=models.CharField(max_length=255, verbose_name='属性ID'),
        ),
        migrations.AlterUniqueTogether(
            name='attrdefinitionmodel',
            unique_together={('model', 'attr_id')},
        ),
    ]
