# Generated by Django 5.2.5 on 2025-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_attrdefinitionmodel_attr_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attrdefinitionmodel",
            name="attr_type",
        ),
        migrations.AlterField(
            model_name="attrdefinitionmodel",
            name="attr_description",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="属性描述"),
        ),
    ]
