# Generated by Django 5.2.5 on 2025-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attrdefinitionmodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrdefinitionmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
