# Generated by Django 5.2.5 on 2025-09-07 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ext_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'definition',
                    models.OneToOneField(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ext_model.modeldefinitionmodel',
                        verbose_name='定义',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=255, verbose_name='编码')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='总结')),
                (
                    'keyword',
                    models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词'),
                ),
                (
                    'web_url',
                    models.CharField(blank=True, max_length=600, null=True, verbose_name='链接'),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('published', '已发布'),
                            ('archived', '已归档'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                (
                    'attr1',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性1'),
                ),
                (
                    'attr2',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性2'),
                ),
                (
                    'attr3',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性3'),
                ),
                (
                    'attr4',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性4'),
                ),
                (
                    'attr5',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性5'),
                ),
                (
                    'attr6',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性6'),
                ),
                (
                    'attr7',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性7'),
                ),
                (
                    'attr8',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性8'),
                ),
                (
                    'attr9',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='属性9'),
                ),
                (
                    'attr10',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性10'),
                ),
                (
                    'attr11',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性11'),
                ),
                (
                    'attr12',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性12'),
                ),
                (
                    'attr13',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性13'),
                ),
                (
                    'attr14',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性14'),
                ),
                (
                    'attr15',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性15'),
                ),
                (
                    'attr16',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性16'),
                ),
                (
                    'attr17',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性17'),
                ),
                (
                    'attr18',
                    models.CharField(blank=True, max_length=6000, null=True, verbose_name='属性18'),
                ),
                ('attr19', models.CharField(blank=True, null=True, verbose_name='属性19')),
                ('attr20', models.TextField(blank=True, null=True, verbose_name='属性20')),
                ('attr21', models.TextField(blank=True, null=True, verbose_name='属性21')),
                ('attr22', models.TextField(blank=True, null=True, verbose_name='属性22')),
                ('attr23', models.TextField(blank=True, null=True, verbose_name='属性23')),
                ('attr24', models.TextField(blank=True, null=True, verbose_name='属性24')),
                ('attr25', models.JSONField(blank=True, null=True, verbose_name='属性25')),
                ('attr26', models.JSONField(blank=True, null=True, verbose_name='属性26')),
                ('attr27', models.JSONField(blank=True, null=True, verbose_name='属性27')),
                ('attr28', models.JSONField(blank=True, null=True, verbose_name='属性28')),
                ('attr29', models.JSONField(blank=True, null=True, verbose_name='属性29')),
                ('attr30', models.JSONField(blank=True, null=True, verbose_name='属性30')),
                (
                    'category',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='content.category',
                        verbose_name='分类',
                    ),
                ),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('path', models.CharField(max_length=600, verbose_name='路径')),
                ('size', models.IntegerField(verbose_name='大小')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('hex', models.CharField(max_length=255, unique=True, verbose_name='哈希值')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                (
                    'collection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='content.content',
                        verbose_name='集合',
                    ),
                ),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Level1Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='level1',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='content.level1category',
                verbose_name='一级分类',
            ),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['code'], name='content_con_code_a3c4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title'], name='content_con_title_98e420_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category'], name='content_con_categor_f747ff_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['state'], name='content_con_state_b2ea28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('collection', 'hex')},
        ),
    ]
