# Generated by Django 5.2.5 on 2025-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='type',
            new_name='mime_type',
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('MARKDOWN', 'MD'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=20, null=True, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图'),
        ),
    ]
