# Generated by Django 5.2.5 on 2025-09-07 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinitionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型名称'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型类型'
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型描述'
                    ),
                ),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '模型定义',
                'verbose_name_plural': '模型定义',
                'db_table': 'attr_model',
            },
        ),
        migrations.CreateModel(
            name='AttrDefinitionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'create_time',
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
                ),
                (
                    'update_time',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('attr_name', models.CharField(max_length=255, verbose_name='属性名称')),
                ('attr_id', models.CharField(max_length=255, verbose_name='属性ID')),
                (
                    'attr_description',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='属性描述'
                    ),
                ),
                ('attr_label', models.CharField(max_length=255, verbose_name='属性标签')),
                (
                    'create_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_create',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建用户',
                    ),
                ),
                (
                    'update_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_update',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新用户',
                    ),
                ),
                (
                    'model',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_model',
                        to='ext_model.modeldefinitionmodel',
                        verbose_name='模型',
                    ),
                ),
            ],
            options={
                'verbose_name': '属性定义',
                'verbose_name_plural': '属性定义',
                'db_table': 'attr_define',
                'unique_together': {('model', 'attr_id')},
            },
        ),
    ]
