# Generated by Django 5.2.5 on 2025-09-06 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="content",
            name="file",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("delete_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("path", models.CharField(max_length=600, verbose_name="路径")),
                ("size", models.IntegerField(verbose_name="大小")),
                ("type", models.CharField(max_length=20, verbose_name="类型")),
                ("order", models.IntegerField(verbose_name="顺序")),
                ("hex", models.CharField(max_length=255, unique=True, verbose_name="哈希值")),
                ("content", models.TextField(blank=True, null=True, verbose_name="内容")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.content",
                        verbose_name="集合",
                    ),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_create",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_update",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "ordering": ("order",),
                "unique_together": {("collection", "hex")},
            },
        ),
    ]
