# Generated by Django 5.2.5 on 2025-09-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MyModelDefinitionModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型名称'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型类型'
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='模型描述'
                    ),
                ),
            ],
            options={
                'verbose_name': '模型定义',
                'verbose_name_plural': '模型定义',
            },
        ),
        migrations.CreateModel(
            name='ConcreteExtModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性1'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性2'
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性3'
                    ),
                ),
                (
                    'attr1',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性1'
                    ),
                ),
                ('attr2', models.IntegerField(blank=True, null=True, verbose_name='测试属性2')),
                ('attr3', models.FloatField(blank=True, null=True, verbose_name='测试属性3')),
                ('attr4', models.DateField(blank=True, null=True, verbose_name='测试属性4')),
                ('attr5', models.TextField(blank=True, null=True, verbose_name='测试属性5')),
                (
                    'attr6',
                    models.JSONField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性6'
                    ),
                ),
                ('attr7', models.TimeField(blank=True, null=True, verbose_name='测试属性7')),
                (
                    'attr8',
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性8'
                    ),
                ),
                (
                    'attr9',
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name='测试属性9'
                    ),
                ),
                (
                    'attr10',
                    models.BooleanField(
                        blank=True,
                        default=False,
                        max_length=255,
                        null=True,
                        verbose_name='测试属性10',
                    ),
                ),
                (
                    'attr11',
                    models.BigIntegerField(blank=True, null=True, verbose_name='测试属性11'),
                ),
                (
                    'attr12',
                    models.SmallIntegerField(blank=True, null=True, verbose_name='测试属性12'),
                ),
                (
                    'attr13',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name='测试属性13',
                    ),
                ),
                ('attr14', models.DurationField(blank=True, null=True, verbose_name='测试属性14')),
                ('attr15', models.DateTimeField(blank=True, null=True, verbose_name='测试属性15')),
                ('attr16', models.UUIDField(blank=True, null=True, verbose_name='测试属性16')),
                (
                    'definition',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='content.mymodeldefinitionmodel',
                        verbose_name='模型定义',
                    ),
                ),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'db_table': 'ext_model',
            },
        ),
        migrations.CreateModel(
            name='MyAttrDefinitionModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('attr_name', models.CharField(max_length=255, verbose_name='属性名称')),
                ('attr_id', models.CharField(max_length=255, verbose_name='属性ID')),
                (
                    'attr_description',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='属性描述'
                    ),
                ),
                ('attr_label', models.CharField(max_length=255, verbose_name='属性标签')),
                (
                    'model',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='content.mymodeldefinitionmodel',
                        verbose_name='模型',
                    ),
                ),
            ],
            options={
                'verbose_name': '属性定义',
                'verbose_name_plural': '属性定义',
                'abstract': False,
                'unique_together': {('model', 'attr_id')},
            },
        ),
    ]
