# Generated by Django 5.2.5 on 2025-09-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteextmodel',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='测试属性2'),
        ),
        migrations.AddField(
            model_name='concreteextmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='测试属性3'),
        ),
        migrations.AddField(
            model_name='concreteextmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='测试属性1'),
        ),
    ]
